<RootWidget>:
    orientation: 'vertical'
    slider_colors: [0.5, 0.5, 0.5]
    canvas.before:
        Color:
            rgb: root.slider_colors
        Rectangle:
            pos: root.pos
            size: root.size
    Slider:
        min: 0
        max: 1
        value: 0.5
        on_value: color_label.text = "Rank " + \
        str(self.value); root.slider_colors = (self.value for i in xrange(3))
    Label:
        id: color_label
        font_size: "50sp"
        text: "Rank 0.5"